<?php

declare(strict_types=1);

if (PHP_SAPI !== 'cli') {
    die;
}

const UNICODE_VERSION = '17.0.0';
const FIRST_CHAR = 0x13000;
const LAST_CHAR = 0x1342F;

$tmpDir = __DIR__ . '/tmp';
if (!is_dir($tmpDir)) {
    mkdir($tmpDir);
}

$charToGardiner = readUnicodeData(downloadUnicodeData());
$gardinerToChar = array_flip($charToGardiner);
$categories = getHieroglyphCategories($charToGardiner);
$charSizes = processSvgFiles('/mnt/c/temp', $charToGardiner);
$bbox = findBoundingBox($charSizes);

saveData(
    'unicode.php',
    [
        'charToGardiner' => $charToGardiner,
        'gardinerToChar' => $gardinerToChar,
        'categories' => $categories,
    ]
);

function bail(string $message): void
{
    fputs(STDERR, "$message\n");
    exit(1);
}

function downloadUnicodeData(): string
{
    global $tmpDir;

    $remoteUrl = sprintf('https://www.unicode.org/Public/%s/ucd/UnicodeData.txt', UNICODE_VERSION);
    $localPath = sprintf('%s/UnicodeData-%s.txt', $tmpDir, UNICODE_VERSION);

    if (is_file($localPath) && is_readable($localPath) && filesize($localPath) > 2 * 1024 * 1024) {
        echo "Unicode data is already present at $localPath\n";
        return $localPath;
    }

    $contents = file_get_contents($remoteUrl);
    file_put_contents($localPath, $contents);

    echo "Downloaded Unicode data file.\n";

    return $localPath;
}

function readUnicodeData(string $filename): array
{
    $result = [];
    foreach (file($filename) as $line) {
        $line = preg_replace('/#.*$/', '', $line);
        $line = trim($line);

        $parts = explode(';', $line);
        if (count($parts) < 8) {
            continue;
        }

        $charNo = (int)base_convert($parts[0], 16, 10);
        
        if ($charNo < FIRST_CHAR) {
            continue;
        }
        if ($charNo > LAST_CHAR) {
            break;
        }

        if (!preg_match('/EGYPTIAN HIEROGLYPH (A?[A-Z][0-9][0-9][0-9][A-Z]?)/', $parts[1], $matches)) {
            continue;
        }

        $name = ucfirst(strtolower($matches[1]));

        $result[$charNo] = $name;
    }

    printf("%d characters found.\n", count($result));

    return $result;
}

function getHieroglyphCategories(array $unicodeData): array
{
    foreach ($unicodeData as $char => $code) {
        $group = preg_replace('/^(Aa|[A-Z]).*$/', '$1', $code);
        $categories[$group][] = $code;
    }

    return $categories;
}

function processSvgFiles(string $dir, array $charToGardiner): array
{
    echo "Loading SVG file information...\n";

    $destDir = __DIR__ . '/svg';
    $result = [];

    foreach (glob("$dir/*.svg") as $i => $filename) {
        if ($i && $i % 100 === 0) {
            echo "  $i\n";
        }
        if (!preg_match('/(\d{5})/', $filename, $matches)) {
            continue;
        }
        $char = (int)$matches[1];
        if ($char < FIRST_CHAR || $char > LAST_CHAR) {
            continue;
        }

        $doc = new DOMDocument();
        $doc->load($filename);
        $nodes = $doc->getElementsByTagName('svg');
        if (!$nodes->count()) {
            bail("No <svg> element found in $filename");
        }
        $svg = $nodes[0];
        $viewBox = $svg->getAttribute('viewBox');
        if (!preg_match('/^-?\d+ -?\d+ \d+ \d+$/', $viewBox)) {
            bail("No valid viewBox found in $filename");
        }

        $result[] = array_map('intval', explode(' ', $viewBox));

        $svg->removeAttribute('xmlns');
        $svg->removeAttribute('xmlns:xlink');
        $svg->removeAttribute('version');

        $contents = $doc->saveXML($svg);

        if ($contents === false) {
            bail("Error saving a transformed $filename");
        }

        file_put_contents("$destDir/$char.svg", $contents);
    }

    return $result;
}

function findBoundingBox(array $sizes): array
{
    $box = [PHP_INT_MAX, PHP_INT_MAX, 0, 0];

    foreach ($sizes as $size) {
        $box[0] = min($box[0], $size[0]);
        $box[1] = min($box[1], $size[1]);
        $box[2] = max($box[2], $size[2]);
        $box[3] = max($box[3], $size[3]);
    }

    echo 'Bounding box: ' . json_encode($box, JSON_PRETTY_PRINT) . "\n";

    return $box;
}

function saveData(string $filename, array $data): void
{
    $timestamp = (new DateTime())->format('Y-m-d H:i:s');
    $content = <<<PHP
    <?php
    // DO NOT EDIT, this is an automatically generated file.
    // Generated by data/generate.php on $timestamp


    PHP;

    $content .= 'return ' . var_export($data, true) . ";\n";

    file_put_contents(__DIR__ . '/' . $filename, $content);
}


