<?php

declare(strict_types=1);

if (PHP_SAPI !== 'cli') {
    die;
}

const UNICODE_VERSION = '17.0.0';
const FIRST_CHAR = 0x13000;
const LAST_CHAR = 0x1342F;

$tmpDir = __DIR__ . '/tmp';
if (!is_dir($tmpDir)) {
    mkdir($tmpDir);
}

$charToGardiner = readUnicodeData(downloadUnicodeData());
$gardinerToChar = array_flip($charToGardiner);
$categories = getHieroglyphCategories($charToGardiner);

saveData(
    'unicode.php',
    [
        'charToGardiner' => $charToGardiner,
        'gardinerToChar' => $gardinerToChar,
        'categories' => $categories,
    ]
);

echo "Generating phonetics arrays.\n";
$gardinerToPhonetic = readPhonetics(__DIR__ . '/phonetics.txt');
$phoneticToGardiner = array_flip($gardinerToPhonetic);

$phonetics = array_values($gardinerToPhonetic);
$phoneticsLc = array_map(strtolower(...), $phonetics);
$lowerCaseIndex = array_combine($phoneticsLc, $phonetics);

saveData(
    'phonetics.php',
    [
        'gardinerToPhonetic' => $gardinerToPhonetic,
        'phoneticToGardiner' => $phoneticToGardiner,
        'lowerCaseIndex' => $lowerCaseIndex,
    ]
);

function bail(string $message): void
{
    fputs(STDERR, "$message\n");
    exit(1);
}

function downloadUnicodeData(): string
{
    global $tmpDir;

    $remoteUrl = sprintf('https://www.unicode.org/Public/%s/ucd/UnicodeData.txt', UNICODE_VERSION);
    $localPath = sprintf('%s/UnicodeData-%s.txt', $tmpDir, UNICODE_VERSION);

    if (is_file($localPath) && is_readable($localPath) && filesize($localPath) > 2 * 1024 * 1024) {
        echo "Unicode data is already present at $localPath\n";
        return $localPath;
    }

    $contents = file_get_contents($remoteUrl);
    file_put_contents($localPath, $contents);

    echo "Downloaded Unicode data file.\n";

    return $localPath;
}

function readUnicodeData(string $filename): array
{
    $result = [];
    foreach (file($filename) as $line) {
        $line = preg_replace('/#.*$/', '', $line);
        $line = trim($line);

        $parts = explode(';', $line);
        if (count($parts) < 8) {
            continue;
        }

        $charNo = (int)base_convert($parts[0], 16, 10);
        
        if ($charNo < FIRST_CHAR) {
            continue;
        }
        if ($charNo > LAST_CHAR) {
            break;
        }

        if (!preg_match('/EGYPTIAN HIEROGLYPH (A?[A-Z][0-9][0-9][0-9][A-Z]?)/', $parts[1], $matches)) {
            continue;
        }

        $name = ucfirst(strtolower($matches[1]));
        $name = preg_replace('/(?<=[a-z])0+/i', '', $name);

        $result[$charNo] = $name;
    }

    printf("%d characters found.\n", count($result));

    return $result;
}

function getHieroglyphCategories(array $unicodeData): array
{
    $categories = [];
    foreach ($unicodeData as $code) {
        $group = preg_replace('/^(Aa|[A-Z]).*$/', '$1', $code);
        $categories[$group][] = $code;
    }

    return $categories;
}

function readPhonetics(string $filename): array
{
    $lines = file($filename) or bail("Could not read $filename");

    $result = [];
    foreach ($lines as $line) {
        $line = trim($line);

        if ($line === '' || $line[0] === '#') {
            continue;
        }

        $parts = preg_split('/\s*=\s*/', $line, 2, PREG_SPLIT_NO_EMPTY);
        if (count($parts) !== 2) {
            bail("Could not parse line '$line'");
        }

        $result[$parts[0]] = $parts[1];
    }

    return $result;
}

function saveData(string $filename, array $data): void
{
    $timestamp = (new DateTime())->format('Y-m-d H:i:s');
    $content = <<<PHP
    <?php
    // DO NOT EDIT, this is an automatically generated file.
    // Generated by data/generate.php on $timestamp


    PHP;

    $content .= 'return ' . var_export($data, true) . ";\n";

    file_put_contents(__DIR__ . '/' . $filename, $content);
}


