<?php

declare(strict_types=1);

const FIRST_CHAR = 0x13000;
const LAST_CHAR = 0x1342F;

$source = $argv[1] ?? __DIR__ . '/tmp';
$dest = $argv[2] ?? __DIR__ . '/fonts/noto';

$unicodeData = loadUnicodeData();

$result = [
    'metadata' => json_decode(file_get_contents("$source/font.json"), true, flags: JSON_THROW_ON_ERROR),
    'characters' => processSvgFiles($source, $dest, $unicodeData['charToGardiner']),
];

saveData("$dest/font.php", $result);

function bail(string $message): void
{
    fputs(STDERR, "$message\n");
    exit(1);
}

function loadUnicodeData(): array
{
    try {
        return require __DIR__ . '/unicode.php';
    } catch (Throwable) {
        bail('Unicode data file not found, run data/generate.php first.');
    }
}

/**
 * @param array<int, string> $charToGardiner
 * @return array<string, mixed>
 */
function processSvgFiles(string $source, string $dest, array $charToGardiner): array
{
    echo "Massaging and analysing SVG files from $source to $dest...\n";

    $result = [];

    foreach (glob("$source/raw*.svg") as $i => $filename) {
        if ($i && $i % 100 === 0) {
            echo "  $i\n";
        }
        if (!preg_match('/(\d{5})/', $filename, $matches)) {
            continue;
        }

        $char = (int)$matches[1];
        $gardinerCode = $charToGardiner[$char] ?? null;
        if (!$gardinerCode) {
            continue;
        }

        $result[$gardinerCode] = processSvg($filename, "$dest/$gardinerCode.svg");
    }

    if (!$result) {
        bail("No raw*.svg files found in $source, run data/extract-svgs.py first.");
    }

    return $result;
}

function processSvg(string $source, string $dest): array
{
    $doc = new DOMDocument();
    $doc->load($source);
    $nodes = $doc->getElementsByTagName('svg');
    if (!$nodes->count()) {
        bail("No <svg> element found in $source");
    }
    $svg = $nodes[0];
    $viewBox = $svg->getAttribute('viewBox');
    if (!preg_match('/^-?\d+ -?\d+ \d+ \d+$/', $viewBox)) {
        bail("No valid viewBox found in $source");
    }

    $result = array_map('intval', explode(' ', $viewBox));

    $svg->removeAttribute('xmlns');
    $svg->removeAttribute('xmlns:xlink');
    $svg->removeAttribute('version');

    $contents = $doc->saveXML($svg);

    if ($contents === false) {
        bail("Error serializing a transformed $source");
    }

    file_put_contents($dest, $contents) ?: bail("Error saving $source");

    return $result;
}

function findBoundingBox(array $sizes): array
{
    $box = [PHP_INT_MAX, PHP_INT_MAX, 0, 0];

    foreach ($sizes as $size) {
        $box[0] = min($box[0], $size[0]);
        $box[1] = min($box[1], $size[1]);
        $box[2] = max($box[2], $size[2]);
        $box[3] = max($box[3], $size[3]);
    }

    echo 'Bounding box: ' . json_encode($box, JSON_PRETTY_PRINT) . "\n";

    return $box;
}

function saveData(string $filename, array $data): void
{
    $timestamp = (new DateTime())->format('Y-m-d H:i:s');
    $content = <<<PHP
    <?php
    // DO NOT EDIT, this is an automatically generated file.
    // Generated by data/prepare-font.php on $timestamp


    PHP;

    $content .= 'return ' . var_export($data, true) . ";\n";

    file_put_contents($filename, $content);
}
