<?php
// DO NOT EDIT, this is an automatically generated file.
// Generated by data/prepare-font.php on 2026-07-13 16:46:17

return array (
  'version' => 1,
  'metadata' => 
  array (
    'name' => 'Test shapes',
    'version' => '∞',
    'copyright' => 'Not eligible (oh c\'mon)',
    'generator' => 'Hands and Mk. I eyeball',
    'numChars' => 4,
  ),
  'boundingBox' => 
  array (
    0 => 0,
    1 => 0,
    2 => 100,
    3 => 100,
  ),
  'characters' => 
  array (
    'A1' => 
    array (
      0 => 0,
      1 => 0,
      2 => 100,
      3 => 100,
    ),
    'A2' => 
    array (
      0 => 0,
      1 => 0,
      2 => 100,
      3 => 100,
    ),
    'A3' => 
    array (
      0 => 0,
      1 => 0,
      2 => 100,
      3 => 100,
    ),
    'A4' => 
    array (
      0 => 0,
      1 => 0,
      2 => 50,
      3 => 100,
    ),
  ),
);
